import React from 'react';
import styles from './DailyBriefing.module.css';

interface DailyBriefingProps {
  name: string;
  text: string;
  generatedAt: string;
  onRegenerate?: () => void;
  loading?: boolean;
}

export function DailyBriefing({ name, text, generatedAt, onRegenerate, loading }: DailyBriefingProps) {
  if (loading) {
    return (
      <div className={styles.skeleton}>
        <div className={styles.skeletonLine} style={{ height: 28, width: '45%', marginBottom: 16 }} />
        <div className={styles.skeletonLine} style={{ height: 14, width: '100%', marginBottom: 8 }} />
        <div className={styles.skeletonLine} style={{ height: 14, width: '92%', marginBottom: 8 }} />
        <div className={styles.skeletonLine} style={{ height: 14, width: '78%', marginBottom: 20 }} />
        <div className={styles.skeletonLine} style={{ height: 12, width: '30%' }} />
      </div>
    );
  }

  return (
    <div className={styles.card}>
      <h2 className={styles.greeting}>🌅 Good morning, {name}!</h2>
      <p className={styles.body}>{text}</p>
      <div className={styles.footer}>
        <span className={styles.generatedAt}>Generated by Task Mom · {generatedAt}</span>
        {onRegenerate && (
          <button className={styles.regenBtn} onClick={onRegenerate}>
            ↺ Regenerate
          </button>
        )}
      </div>
    </div>
  );
}

export default DailyBriefing;
